name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '1.25.x'
          cache: true

      - uses: arduino/setup-task@v2
        with:
          version: 3.39.2
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - uses: golangci/golangci-lint-action@v7
        with:
          version: v2.7.0

      - run: task build
      - run: task test ./...
      - run: task lint
      - run: task vulncheck
